#+TITLE: Exercises for Chapter 2
* EXERCISES SECTION 2.1.1
** DONE Exercise 2.1
What are the differences between ~int~, ~long~, ~long long~, and ~short~?
Between an unsigned and a signed type? Between a float and a double?

Speaking of the minimum size, ~short~ <= ~int~ <= ~long~ <= ~long long~
signed: with +/-; unsigned: without +/-
~float~ is less precise than ~double~
** DONE Exercise 2.2
To calculate a mortgage payment, what types would you use for the rate,
principal, and payment? Explain why you selected each type.

+ rate: ~float~ is enough for the rate, but ~double~ is also fine
+ principle: ~float~ for the point part
+ payment: ~int~ mostly likely it will be
** DONE Exercise 2.3
What output will the following code produce?
#+BEGIN_SRC cpp
unsigned u = 10, u2 = 42;
std::cout << u2 - u << std::endl;
std::cout << u - u2 << std::endl;
int i = 10, i2 = 42;
std::cout << i2 - i << std::endl;
std::cout << i - i2 << std::endl;
std::cout << i - u << std::endl;
std::cout << u - i << std::endl;

// on my machine
// 32
// 4294967264
// 32
// -32
// 0
// 0
#+END_SRC
** DONE Exercise 2.4
Write a program to check whether your predictions were correct. If not, study this section until you understand what the problem is.
See [[file:./ex2_3.cpp][ex2_3.cpp]]
* EXERCISES SECTION 2.1.3
** TODO Exercise 2.5
Determine the type of each of the following literals. Explain the differ-
ences among the literals in each of the four examples:
#+BEGIN_EXAMPLE
(a) ’a’,L’a’,"a",L"a"
(b) 10,10u,10L,10uL,012,0xC
(c) 3.14,3.14f,3.14L
(d) 10,10u,10.,10e-2
#+END_EXAMPLE
** DONE Exercise 2.6
What, if any, are the differences between the following definitions:
#+BEGIN_SRC cpp
int month = 9, day = 7; // integer literals, signed
int month = 09, day = 07; // 0 marks `09` should be an octal but 9 is invalid
// Of course since in octal 8 is the highest digit, thus causing compilation error

ex2_6.cpp:5:15: error: invalid digit "9" in octal constant
    5 |   int month = 09, day = 07;
      |               ^~
ex2_6.cpp: In function ‘int main()’:
ex2_6.cpp:7:16: error: ‘day’ was not declared in this scope
    7 |   std::cout << day << std::endl;
      |                ^~~
#+END_SRC
** TODO Exercise 2.7
What values do these literals represent? What type does each have?
#+BEGIN_EXAMPLE
(a) "Who goes with F\145rgus?\012"
(b) 3.14e1L (c) 1024f (d) 3.14L
#+END_EXAMPLE
** DONE Exercise 2.8
Using escape sequences, write a program to print ~2M~ followed by a new-
line. Modify the program to print ~2~, then a tab, then an ~M~, followed by a newline.
* EXERCISES SECTION 2.2.2
** DONE Exercise 2.11
Explain whether each of the following is a declaration or a definition:
#+BEGIN_EXAMPLE
(a) extern int ix = 1024; // definition
(b) int iy;
// definition and the variable is initialized as zero if defined outside any function
// or is uninitialized if inside a function
(c) extern int iz; // declarition
#+END_EXAMPLE
