#+TITLE: Exercises Chapter - 1
* EXERCISES SECTION 1.2
** Exercise 1.3
Write a program to print Hello, World on the standard output.
#+BEGIN_SRC cpp
#include <iostream>

int main()
{
  std::cout << "Hello World" << std::endl;
  return 0;
}
#+END_SRC
** Exercise 1.4
Our program used the addition operator, +, to add two numbers. Write a program that uses the multiplication operator, *, to print the product instead.
#+BEGIN_SRC cpp
#include <iostream>

int main()
{
  std::cout << "Enter two numbers:" << std::endl;
  int v1 = 0, v2 = 0;
  std::cin >> v1 >> v2;
  std::cout << "The product of " << v1 << " and " << v2
            << " is " << v1 * v2 << std::endl;
  return 0;
}
#+END_SRC
** Exercise 1.5
We wrote the output in one large statement. Rewrite the program to use
a separate statement to print each operand.
#+BEGIN_SRC cpp
#include <iostream>

int main()
{
  std::cout << "Enter two numbers:" << std::endl;
  int v1 = 0, v2 = 0;
  std::cin >> v1;
  std::cin >> v2;

  std::cout << "The product of ";
  std::out << v1;
  std::out << " and ";
  std::out << v2;
  std::out << " is ";
  std::out << v1 * v2;
  std::out << std::endl;
  return 0;
}
#+END_SRC

** Exercise 1.6
Explain whether the following program fragment is legal.
#+BEGIN_SRC cpp
std::cout << "The sum of " << v1;
          << " and " << v2;
          << " is " << v1 + v2 << std::endl;
#+END_SRC
If the program is legal, what does it do? If the program is not legal, why not? How would you fix it?

It is not legal. =;= terminates a statement so that line 2 and line 3 are not legal and will send the stream to nowhere. To fix it, simply add ~std::cout~ to the beginning of line 2 and line 3:
#+BEGIN_SRC cpp
std::cout << "The sum of " << v1;
std::cout << " and " << v2;
std::cout << " is " << v1 + v2 << std::endl;
#+END_SRC
* EXERCISES SECTION 1.3
** Exercise 1.7
Compile a program that has incorrectly nested comments.
#+BEGIN_SRC cpp
// incorrctly nested comments
#include <iostream>
int main()
{
  /* Incorrectly nested /*   */
   * multiline comments
   */
}
#+END_SRC
I got:
#+BEGIN_EXAMPLE
ex1_7.cpp: In function ‘int main()’:
ex1_7.cpp:5:6: error: ‘multiline’ was not declared in this scope
    5 |    * multiline comments
      |      ^~~~~~~~~
#+END_EXAMPLE
** Exercise 1.8
Indicate which, if any, of the following output statements are legal:
#+BEGIN_SRC cpp
std::cout << "/*";
std::cout << "*/";
std::cout << /* "*/" */;
std::cout << /* "*/" /* "/*" */;
#+END_SRC
After you’ve predicted what will happen, test your answers by compiling a program with each of these statements. Correct any errors you encounter.

I think the 3rd will cause error because it is nested. The 4th will also be problematic because the  output  =/*=.

Leaving only the 3rd in place will get
#+BEGIN_EXAMPLE
ex1_8.cpp:7:22: warning: missing terminating " character
    7 |   std::cout << /* "*/" */;
      |                      ^
ex1_8.cpp:7:22: error: missing terminating " character
    7 |   std::cout << /* "*/" */;
      |                      ^~~~~
ex1_8.cpp: In function ‘int main()’:
ex1_8.cpp:10:3: error: expected primary-expression before ‘return’
   10 |   return 0;
      |   ^~~~~~
#+END_EXAMPLE
